name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-api

jobs:

  build-push:

    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build and push api
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        file: api/Dockerfile
        tags: ghcr.io/${{ github.repository }}-api:latest  

    - name: Build and push web
      uses: docker/build-push-action@v5
      env:
        VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
      with:
        context: webapp
        push: true
        file: webapp/Dockerfile
        tags: ghcr.io/${{ github.repository }}-web:latest
